<a href="https://colab.research.google.com/github/mohamadhayeri9/tensorflow_example/blob/master/classification_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [3]:
tf.version.VERSION

'2.2.0-rc3'

In [0]:
mnist = tf.keras.datasets.mnist

In [0]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# normalization
# Data normalization means transforming all variables in the data to a specific range.
x_train, x_test = x_train / 255.0, x_test / 255.0

In [0]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(.2),# prevent overfitting
    tf.keras.layers.Dense(10)#number 0 to 9 mean 10
])

In [0]:
predictions = model(x_train[:1]).numpy()

In [17]:
predictions

array([[-0.14365077,  0.11912027, -0.12686539,  0.40704444, -0.06376003,
         0.3604337 , -1.5630717 , -0.02100334,  0.25602028, -0.5254723 ]],
      dtype=float32)

In [18]:
tf.nn.softmax(predictions).numpy() # convert(normalize) to probabilisties

array([[0.08820798, 0.11471702, 0.08970108, 0.15299307, 0.09554412,
        0.14602558, 0.02133345, 0.09971786, 0.13154756, 0.06021225]],
      dtype=float32)

In [0]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [20]:
loss_fn(y_train[:1], predictions).numpy()

1.9239734

In [0]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [22]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2927 - accuracy: 0.9143
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1423 - accuracy: 0.9571
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1086 - accuracy: 0.9664
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0903 - accuracy: 0.9721
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0751 - accuracy: 0.9763


In [23]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0776 - accuracy: 0.9762


[0.0775776281952858, 0.9761999845504761]

In [0]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [25]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.14612907e-07, 1.54712332e-08, 2.46095660e-05, 1.54855676e-04,
        2.17014975e-10, 2.03038880e-07, 2.42805450e-12, 9.99809206e-01,
        7.77170555e-07, 9.88090778e-06],
       [3.51563401e-08, 2.66597170e-04, 9.99653697e-01, 7.54592475e-05,
        1.93420966e-16, 7.17528962e-07, 1.58098715e-06, 2.76739027e-12,
        2.06051982e-06, 4.45672721e-14],
       [2.90752631e-08, 9.99672174e-01, 1.82367112e-05, 2.70636377e-07,
        2.82911860e-05, 2.21899495e-06, 6.87433885e-06, 2.50696816e-04,
        2.09312966e-05, 2.40767747e-07],
       [9.99841809e-01, 2.17901780e-10, 1.20525976e-04, 3.64275479e-07,
        2.93079410e-08, 9.39083350e-07, 3.07354821e-05, 3.38217569e-06,
        6.87376428e-07, 1.59649494e-06],
       [2.55408031e-05, 4.88696088e-08, 1.15855873e-04, 9.85171710e-07,
        9.25816119e-01, 4.68275766e-06, 5.69826843e-05, 4.61684802e-04,
        3.52654351e-05, 7.34828785e-02]], dtype=float32)>